spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8886
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8886/eureka/,http://peer1:8885/eureka/,http://peer3:8887/eureka/
    registerWithEureka: true
    fetchRegistry: true