
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testjpa?useUnicode=true&characterEncoding=utf8&charactreSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create # 第一次建表用 create ，后面用 Update
    show-sql: true

